[project]
name = "flaskr"
version = "0.0.0"
description = "it's like a dictionary but backwards"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
